{{- if .Values.masterKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm-gateway.masterKeySecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "litellm-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.masterKey.existingSecretKey }}: {{ .Values.masterKey.value | quote }}
{{- end }}
